schema_version = "1.0.0"
id = "console_mirror_utility"
version = "1.0.0"
name = "Console Mirror"
tagline = "Redirects system console output to Blender Text Editor"
type = "add-on"
blender_version_min = "4.2.0"
maintainer = "unclepomedev <unclepome.dev@gmail.com>"
license = ["SPDX:GPL-3.0-or-later"]

[description]
text = "Mirrors system console output (stdout/stderr) to a Blender Text Block for easy debugging."

[urls]
website = "https://github.com/unclepomedev/blender_console_mirror"